// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ahJNsL4sfy4TVlc9jGymrkJPlbbJ0-w',
    appId: '1:485352211339:web:b7dab78afe4c72238c658e',
    messagingSenderId: '485352211339',
    projectId: 'hospicare-app22',
    authDomain: 'hospicare-app22.firebaseapp.com',
    storageBucket: 'hospicare-app22.appspot.com',
    measurementId: 'G-789NMP5VQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLVHFxa-cISjQN5KG-2NVdajSbtSSYsqo',
    appId: '1:485352211339:android:e2ed5c416dcf89d28c658e',
    messagingSenderId: '485352211339',
    projectId: 'hospicare-app22',
    storageBucket: 'hospicare-app22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxINLHMgzWmjAB6rG7e_PGMvWI5go0bO0',
    appId: '1:485352211339:ios:fc99817436fcee558c658e',
    messagingSenderId: '485352211339',
    projectId: 'hospicare-app22',
    storageBucket: 'hospicare-app22.appspot.com',
    iosClientId:
        '485352211339-pfrk3ihl2fjr70g54lp6sma44cisvhc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospicareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxINLHMgzWmjAB6rG7e_PGMvWI5go0bO0',
    appId: '1:485352211339:ios:fc99817436fcee558c658e',
    messagingSenderId: '485352211339',
    projectId: 'hospicare-app22',
    storageBucket: 'hospicare-app22.appspot.com',
    iosClientId:
        '485352211339-pfrk3ihl2fjr70g54lp6sma44cisvhc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospicareApp',
  );
}
